### ISSUE TITLE
864697 - Stab Wound X value isn't good. I hit with daggers twice this combat chain and X = 1 instead of X = 2

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#331] opened 2023-03-06 14:20 UTC
![image](https://user-images.githubusercontent.com/26232486/223135882-15377f2d-16b7-4d69-9744-959bd38dee12.png)

**Comment by PvtVoid** [comment] 2023-03-06 14:22
I tested with Flick Knives and it does the same. Always X = 1
![image](https://user-images.githubusercontent.com/26232486/223136794-7f91a8fb-be22-4184-a230-51bdc89b74a1.png)

**Comment by OotTheMonk** [comment] 2023-03-07 00:15
Almost certainly a duplicate of https://github.com/Talishar/Talishar/issues/321

**Closed by OotTheMonk** 2023-03-07 00:15 UTC
