### ISSUE TITLE
Levia Redeemed bug

### ISSUE THREAD

**Issue by Dnist76** [Talishar/Talishar#649] opened 2023-10-09 06:51 UTC
This has happened quite a few times.  If I opt for quick rematch with levia (CC), when the new game populates the levia redeemed is missing from the permanents area on the interface and obviously will not trigger at 13 or 2 life for either Blasmophet or LR.

**Comment by OotTheMonk** [comment] 2023-12-16 19:35
I believe this is an issue with the inventory not getting added to the submitted deck file at all:
![image](https://github.com/Talishar/Talishar/assets/77394768/d08a3496-05d2-471f-bfe2-29db08318ce3)

**Comment by OotTheMonk** [comment] 2023-12-16 19:36
It looks like at the very least the inventory is being stored in the submitted deck file, which means it should theoretically come back when doing the rematch; not sure why it is not (I am easily able to reproduce this issue):
![image](https://github.com/Talishar/Talishar/assets/77394768/ea6491a8-4b3a-44d4-a283-214c97f8db42)

**Comment by OotTheMonk** [comment] 2023-12-16 19:38
After conceding, it is still there:
![image](https://github.com/Talishar/Talishar/assets/77394768/dba3c842-8d71-4e4d-ae2e-c1814454e610)

**Comment by OotTheMonk** [comment] 2023-12-16 19:45
Fixed in commit 0afcfc0f7

**Closed by OotTheMonk** 2023-12-16 19:45 UTC
Labels: bug
