### ISSUE TITLE
864697 - Flick Knives doesn't let you choose which dagger to "throw" (break)

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#332] opened 2023-03-06 14:26 UTC

**Comment by OotTheMonk** [comment] 2023-03-07 00:15
Suspect this is a duplicate of https://github.com/Talishar/Talishar/issues/321

**Closed by OotTheMonk** 2023-03-07 00:15 UTC

**Comment by PvtVoid** [comment] 2023-03-07 08:18
I tested and it's in fact bugged only with Spider's Bite 👍🏼
