### ISSUE TITLE
JSONCards need an enum for if the card is face up / face down

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#165] opened 2023-01-13 01:27 UTC
Add an enum for all cards, something like cardFacing, I'm not sure, pick a better name.

cardFacing = null -> default for zone (eg face down in arsenal face up in banish)
cardFacing = "FACEUP" -> card is face up (eg face up in arsenal)
cardFacing = "FACEDOWN" -> card is face down (eg face down banish, intimidated)

Having null be default for the zone means we don't have to add this everywhere. Can just have it where it matters (intimidate and face up in arsenal, basically, and maybe some future case where you banish a card face down somewhere to reveal it later)

**Comment by OotTheMonk** [comment] 2023-02-15 02:53
I believe this is a duplicate of https://github.com/Talishar/Talishar/issues/186

**Closed by OotTheMonk** 2023-02-15 02:53 UTC
Labels: enhancement
