### ISSUE TITLE
[2636151] - Courage Token/Boltyn Buff are missing from the Chain Link Summary

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#567] opened 2023-09-12 07:54 UTC
<img width="880" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/9b8fd0e2-cd76-4136-b6d5-a561ba2d3e75">

**Comment by OotTheMonk** [comment] 2023-09-20 23:46
The main use of this popup is to show the total damage, if it was a hit, and which cards are there in case you're looking to count how many cncs the opponent has used for instance; while the chain is open, it won't be in this discard. I'd have to think about if I would want it to show all the buffs and everything. It could get confusing with things like rain razors that apply to multiple chain links, or non-attack action cards that contribute buffs. If it shows those, this is no longer as useful for knowing which cards are still on the combat chain waiting to get put into the graveyard (or wherever else based on outstanding game effects).

Closing this as working as intended for now, but you are welcome to re-submit a prototype or mockup of a re-imagining of this popup that works for the above use cases, and also shows all the other effects that applies to the chain link. The data is all there it's just a matter of arranging it in a way that is most suitable.

**Closed by OotTheMonk** 2023-09-20 23:46 UTC
