### ISSUE TITLE
871154 - We cannot reorder the triggers from the new Outsider tokens

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#337] opened 2023-03-07 08:30 UTC
Source: https://fabtcg.com/articles/rules-reprise-10-outsider-heroes-and-tokens/

When you control two or more of these tokens, the turn player is the one that decides the order that they trigger. Because all of these trigger at the end of YOUR turn, you are able to choose the order that they resolve.

Please note that if you are deciding the order of 3 or more triggered-layers, you must decide the order for all of them before the first one resolves. You can NOT choose to resolve one, then decide the order of the remaining triggers based on the result of the first.

It is also important to remember that abilities that trigger “at the beginning of your/the end phase”, trigger and resolve before you perform any end of turn procedures, such as arsenaling a card, putting pitched cards to the bottom of your deck, and drawing your next hand.

Bloodrot Pox vs Inertia:
You may choose to resolve Bloodrot Pox’s trigger before Inertia’s trigger. This allows you to pitch cards to prevent damage from Bloodrot Pox before you put all the cards in your hand on the bottom of your deck from Inertia.

Ponder vs Inertia:
You may choose to put all the cards in your hand and arsenal on the bottom of your deck from Inertia before you draw a card from Ponder.

**Comment by OotTheMonk** [comment] 2023-03-08 00:50
Duplicate of https://github.com/Talishar/Talishar/issues/324 which is fixed

**Closed as completed by OotTheMonk** 2023-03-08 00:50 UTC
