### ISSUE TITLE
[2673653] - Spellbane Aegis pop-up shows even if the gem is turned off

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#570] opened 2023-09-16 06:07 UTC
Not sure if this is intended like this. The gem works fine for the Spellvoid from my Halo of Illumination in this game, but not for the Spellbane Aegis. It always shows-up so it's not game-breaking.
<img width="348" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/44a4f7c9-77d4-4c54-ab5c-ecc79efef20e">

**Comment by OotTheMonk** [comment] 2023-09-19 00:09
I believe this should be fixed now -- thanks @KuKetto !!

**Closed by OotTheMonk** 2023-09-19 00:09 UTC

**Comment by PvtVoid** [comment] 2023-09-20 10:40
I played again today and it seems to still be happening. The spellvoid popup was up when the gem was turned off :(

**Comment by KuKetto** [comment] 2023-09-20 11:27
Yes at the time I was testing on legacy client. So there is 3 state:
- 2 = always hold
- 1 = hold
- 0 = don't hold

The problem is that the token is created as 2, when you turn it on it becomes 1. But when you turn it off again it will have a value of 0 instead of 2. The legacy client does not render the gem on the token if the state is 2 so while i was testing it, i mocked it to have a default value of 0. However in the new front end it renders with the value of 2 so yes, the current fix does not work indeed, sorry about that.

I will set the aegis token's default value to 0, so it will render the gem in the legacy client as well and it will make my previous fix work.

Keep in my that as far as I know, it searches for these spellvoids before the the arcane damage dealing gets off the stack. So if you turn on the gem while you are deciding how much you want to pay on arcane barrier it won't offer you to prevent damage
