### ISSUE TITLE
931029 - [Bug] Cyclone Roundhouse doesn't trigger

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#388] opened 2023-03-15 07:57 UTC
I am not sure if the card isn't coded yet (Although it doesn't appear in the list). This is a trigger that happens when players move to the reaction step. Both players have an opportunity to respond to that trigger. After that trigger resolves both players receive priority in the reaction step to act before the game moves to the damage step.

![image](https://user-images.githubusercontent.com/26232486/225243387-42a54bdb-c22a-40a1-a79f-d98faa35ca49.png)

The previous attack was Spinning:

![image](https://user-images.githubusercontent.com/26232486/225243459-1742e42c-ea18-445d-b1f7-211b3be034b5.png)

Source: https://fabtcg.com/resources/rules-and-policy-center/release-notes/outsiders/

**Comment by OotTheMonk** [comment] 2023-03-16 01:38
Duplicate of #370

**Closed by OotTheMonk** 2023-03-16 01:38 UTC
