### ISSUE TITLE
Change reset password email link to use new FE

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#424] opened 2023-04-02 03:57 UTC
> I couldn't log in anymore so I reset my password, but when I try to open the link in the mail I get this error: "Unexpected Application Error!
> 404 Not Found"

**Comment by LaustinSpayce** [comment] 2023-04-02 04:07
Duplicate of #423 423

**Comment by OotTheMonk** [comment] 2023-04-02 13:49
Closing because this is a duplicate of 423 as noted by Laustin above

**Closed by OotTheMonk** 2023-04-02 13:49 UTC
