### ISSUE TITLE
Undefined array key 1 in /opt/lampp/htdocs/game/Search.php

### ISSUE THREAD

**Issue by donutboyy** [Talishar/Talishar#306] opened 2023-02-23 15:57 UTC
![image](https://user-images.githubusercontent.com/47971350/220960676-cccf68cb-86b0-40f7-bdfb-5f984682b624.png)

**Comment by OotTheMonk** [comment] 2023-02-24 01:40
I suspect this is a duplicate of https://github.com/Talishar/Talishar/issues/176

If the opponent was not the emperor, let me know. But I don't think we can do anything else about it, since we don't have a bug report game id. Next time you find a bug, can you hit the Report Bug button in the menu, and include the number it gives you in the issue ticket? That way we can pull in the exact gamestate from when the bug occurred to take a closer look.

**Closed by OotTheMonk** 2023-02-24 01:40 UTC

**Comment by donutboyy** [comment] 2023-02-24 01:50
Ah my bad, didn't manage find the duplicate issue...

But yes it was against an emperor and I'll make sure to report it on through the menu if I encounter it again 😅
