### ISSUE TITLE
[2133201] - V for Valor cost isn't properly coded. Charging is before the ":" and is part of the cost. 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#531] opened 2023-07-21 12:23 UTC
Currently, you can play V for Valor event if your hand is empty and you don't have a card in hand. The **Charge** is mandatory.

You should refer to the release notes to code cards. It could help prevent a big amount of bugs. 
![image](https://github.com/Talishar/Talishar/assets/26232486/714d78f3-a71c-4085-905b-08d81348ddfa)

**Comment by LaustinSpayce** [comment] 2023-07-22 01:20
Thank you for your report. We look forward to receiving the release notes from you before LSS publish them. :)

**Comment by PvtVoid** [comment] 2023-07-22 07:41
You are still passive aggressive? Its a real issue, chill out Laustin it's ok 😅

It's good feedback, when I was fixing bugs on release day of the release note I would open it and go through cards fixing the bugs and reading the notes. It doesn't have to be there before you start coding the cards.

Flesh and Blood is hard and this is an extremely good tool for bug fixing 😁

**Comment by OotTheMonk** [comment] 2023-07-24 06:44
This is not happening for me. If you find a bug, please try to hit report bug in the menu as that can help reproduce the issue. Please refrain from adding passive-aggressive comments in bug reports. Talishar devs are well aware of set release notes. Closing as not able to reproduce.
![image](https://github.com/Talishar/Talishar/assets/77394768/86421d8a-05bd-4990-932f-b7bb791c4e1c)

**Comment by PvtVoid** [comment] 2023-07-24 06:50
2167413 - Try with a card in hand and 0 floating. You can activate it, then pitch and not pay the charge cost. Your condition is probably to have 1 card in hand. But the condition needs to be: Have 2 cards in hand or 1 card in hand + floating resources.

In the screenshot below I haven't charged but I manage to play the card.
![obraz](https://github.com/Talishar/Talishar/assets/26232486/26caf235-b035-4262-896d-563778ef2eb5)
![obraz](https://github.com/Talishar/Talishar/assets/26232486/e52d4707-c5bc-44d4-a9d5-6dca2ce69a62)

**Comment by PvtVoid** [comment] 2023-07-24 07:01
I tried to reopen the issue, but I don't have permission. I hope it notified you at least 👍🏼

**Comment by OotTheMonk** [comment] 2023-07-24 07:25
Fixed by reverting if you don't have a card to charge 
![image](https://github.com/Talishar/Talishar/assets/77394768/3b74f145-3f31-469b-af87-50917e99f2e2)

**Closed by OotTheMonk** 2023-07-24 07:25 UTC
