### ISSUE TITLE
[BUG] - Sounds Spam - Space bar event key can be spam and annoy opposing player. Spamming the Priority Sound + Reload() / CheckReloadNeeded()

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#703] opened 2024-01-07 07:21 UTC
I've tried to fix it, but didn't manage. Can be replicated just by spamming space bar against yourself on local. 

![image](https://github.com/Talishar/Talishar/assets/26232486/170680aa-788c-4121-baae-5426e559b300)

**Comment by OotTheMonk** [comment] 2024-01-20 15:05
This was caused by flagging the game state for an update when the non-acting player tried to make an illegal move (in your example, passing when they do not have priority to pass). There is validation to keep them from editing the gamestate itself, but it would still flag both players for a reload. Part of the reload logic is checking if you have priority, and making the ping noise if so. Hence the annoying ping spam. Fixed in 5f921550f.

**Closed by OotTheMonk** 2024-01-20 15:05 UTC
Labels: bug, critical
