### ISSUE TITLE
Messages for targeting heroes in react FE show HTML. We need to change these to our escaped methods

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#259] opened 2023-02-07 16:55 UTC
![3EE551A1-5A12-4940-8186-C98E362CB1C2](https://user-images.githubusercontent.com/5060535/217311468-4ce9e435-f746-4fa3-a2b0-b0037a9fe6c7.png)

In cases like this it needs to be fixed up

**Comment by OotTheMonk** [comment] 2023-02-08 00:40
This is the format we decided:
{{card name|WTR005|B}}

**Comment by OotTheMonk** [comment] 2023-02-08 00:50
For cross compatibility, we'll likely need to convert the old fe to use this same scheme.

**Comment by LaustinSpayce** [comment] 2023-02-08 15:00
Are you able to have the $isReactFE  aria ke read? There’s no problem with the chat. It’s just the inline ones. Have them use the new formatting if $isReactFE no need to change for everything then?

**Comment by OotTheMonk** [comment] 2023-02-15 02:53
I believe this one is a duplicate of https://github.com/Talishar/Talishar/issues/207

**Closed by OotTheMonk** 2023-02-15 02:53 UTC
