### ISSUE TITLE
Somebody made a compcc game with no hero

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#441] opened 2023-04-05 14:32 UTC
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5060535/230113196-ea12546e-ccab-4105-9e3f-75862d735b56.png">

Spooky

**Comment by tickct** [comment] 2023-04-05 17:17
So I found a game in progress with no hero on the main screen, when I clicked in it was a Boltyn

{"p1Hero":"","p2Hero":"OUT091","secondsSinceLastUpdate":3,"gameName":"1097714"}, GameID: 1097714

**Comment by OotTheMonk** [comment] 2023-04-10 23:56
I suspect this was caused by player 1 disconnecting, which cleared out their hero, then player 1 reconnects. Fixed in 6ae7b0ad

**Closed by OotTheMonk** 2023-04-10 23:56 UTC
