### ISSUE TITLE
[2212936] - Phantasmal Symbiosis doesn't transform my aura to Illusionist

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#545] opened 2023-07-27 12:23 UTC
I played Phantasmal Symbiosis named Frost Hex and wanted to destroy the Illusionist Frost Hex to replace it with an aura I had from hand with Crown of Reflection.

The crown didn't allow me to choose Frost Hex. It picked automatically my Spectral Shield and destroyed it to let me play an aura.

I don't know if this requires a lot of changes or simply because the effect is only on the opponent's side of the field. Maybe it needs to be added globally to both players.

![image](https://github.com/Talishar/Talishar/assets/26232486/aaf2ad3a-3577-48f4-9a0e-1481b65cb137)
![image](https://github.com/Talishar/Talishar/assets/26232486/e01bfe06-a676-4c11-b5b3-72bd9087c78a)
![image](https://github.com/Talishar/Talishar/assets/26232486/75893409-c69b-494f-8709-50de139f14b5)

**Comment by PvtVoid** [comment] 2023-07-27 12:25
I wanted to add that I am not sure which part of the card is manual. 
+ the CardLink is missing from this write log.
![image](https://github.com/Talishar/Talishar/assets/26232486/eb1efde0-9710-4376-a253-a2a484acbcb3)

**Comment by OotTheMonk** [comment] 2023-07-29 14:27
Duplicate of #415

**Closed by OotTheMonk** 2023-07-29 14:27 UTC
