### ISSUE TITLE
[No Game ID] - hit effect from Soaring Strike and Mounting Anger aren't coded to be reorderable. It makes it impossible to from from MoM first.

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#509] opened 2023-06-03 11:28 UTC
Same case from Rainbow League so I don't have a Game ID. I bet that soaring strike and mounting anger were just never coded to be reorderable.

![obraz](https://github.com/Talishar/Talishar/assets/26232486/c798c83d-c6f0-442e-9797-fc5264e0d656)

**Comment by OotTheMonk** [comment] 2023-06-23 23:43
Duplicate of #244

**Closed by OotTheMonk** 2023-06-23 23:43 UTC
