### ISSUE TITLE
Cards don't apperar in late game.

### ISSUE THREAD

**Issue by eraseface** [Talishar/Talishar#385] opened 2023-03-14 23:19 UTC
Hello team. Playing kano since yesterday, always at the end of games, some cards don't appear. I try to refresh it but it doesn't work. Soon, I would like to report. This week, we will finish a tournament with 48 players in Brazil. It would be great if the team could fix it by then.
![Screenshot_3](https://user-images.githubusercontent.com/127904429/225163294-53351ddd-d071-458b-8d69-a8208b4d7770.png)

**Comment by OotTheMonk** [comment] 2023-03-16 01:39
Hi, I think I responded to you in discord too. The issue was potion of luck was shuffling non-cards into the deck. The issue is fixed in revision e4245f78. Thanks for the report!

**Closed by OotTheMonk** 2023-03-16 01:39 UTC
