### ISSUE TITLE
Professional Enforment

### ISSUE THREAD

**Issue by Tchamber5** [Talishar/Talishar#73] opened 2022-10-09 16:23 UTC
9/18	

Don't allow undos	

Mention: 2	

https://discord.com/channels/865412150125789214/971928581267664936/1017977175422545950

**Comment by OotTheMonk** [comment] 2023-01-19 01:16
This is a duplicate of #68 (require opponent permission to undo)

**Closed by OotTheMonk** 2023-01-19 01:16 UTC
